- name: Beanstalk Deploy
uses: einaregilsson/beanstalk-deploy@v20
with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: inso-production
        environment_name: Insoproduction-env
        version_label: 12345
        region: us-east-1