name: Deploy main
on:
  push:
    branches:
    - main

  build:
    runs-on: ubuntu-latest
    steps:

    - run: echo "::workflow-command :: eb status Insoproduction-env"

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: inso-production
            environment_name: Insoproduction-env
            version_label: 12345
            region: us-east-1