name: Deploy main
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - run: echo "::workflow-command::eb status Insoproduction-env"

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main